description: >
  Update Strigo classe from Zenika training with specific config.
usage:
  version: 2.1

  orbs:
    training-material: zenika/training-material@w.x
    ztraining2strigo: zenika-training/ztraining2strigo@y.z

  workflows:
    version: 2

    build-and-update:
      jobs:
        - training-material/build
        - ztraining2strigo/update:
            config-file: strigo.custom.json
            requires:
              - training-material/build
            context: strigo-api
